### ISSUE TITLE
Wrapping ZKUI With Docker

### ISSUE THREAD

**Issue by medined** [DeemOpen/zkui#1]
https://github.com/medined/docker-zookeeper - Thanks for sharing this web application. I wrapped it with a Docker image and a script to start a three-node ensemble.

**Comment by dylanmei** [comment]
This Docker image has been very helpful! However, I've had to do some magic to get the `zkServer` setting into the config.cfg from environment variables.

@ptrk Are we open to exposing the list of servers (and possibly other settings) as an environment variable?
