### ISSUE TITLE
Bind zkui on 127.0.0.1

### ISSUE THREAD

**Issue by aseev-xx** [DeemOpen/zkui#13]
I need to run the application on 127.0.0.1:9090 but I do not see the necessary options in the config file, and also in the source code (eg, serverHost = 127.0.0.1). Please tell me how to do it and is it possible?

**Comment by arjunsurendra04** [comment]
There is no need of a serverHost property. When you start the server by default you can access
http://localhost:9090 or http://127.0.0.1:9090

**Comment by aseev-xx** [comment]
The fact is that in this case I do not want the application to be available at hostname:9090. I want to proxy requests, for example, nginx. 
The application itself should not look outside.
