### ISSUE TITLE
build error--`Plugin execution not covered by lifecycle configuration: org.javalite:activejdbc-instrumentation

### ISSUE THREAD

**Issue by htw2012** [DeemOpen/zkui#23]
Hi, when I import the project,I found the build error,like:
`Plugin execution not covered by lifecycle configuration: org.javalite:activejdbc-instrumentation:1.4.1:instrument (execution: default, phase: process-
 classes)
`
Error occurs in pom.xml: 
`<plugin>
                <groupId>org.javalite</groupId>
                <artifactId>activejdbc-instrumentation</artifactId>
                <version>1.4.1</version>
                <executions>
                    <execution>
                        <phase>process-classes</phase>
                        <goals>
                            <goal>instrument</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>`

Could you give me some tips to fix it?

Thank you for your help.

**Comment by arjunsurendra04** [comment]
You might be using private maven repository hence its not finding the jar.
