### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by dirtdiver512** [DeemOpen/zkui#4]
New to git, but I cloned this and do not see the file zkui-2.0-SNAPSHOT-jar-with-dependencies.jar that is supposed to run it...?

thanks

**Comment by lambdaupb** [comment]
Yes you are. This app in only distributed in source form. You need to get maven and then, in a terminal, call "mvn package" in the directory of this project.

For further help, have a look at maven howtos and youtube videos :)
